steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/tactile-atlas-428811-g4/github.com/andrewmarkallen/marka.berlin:$COMMIT_SHA', '.']

  # Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 
          'europe-west1-docker.pkg.dev/tactile-atlas-428811-g4/github.com/andrewmarkallen/marka.berlin:$COMMIT_SHA']

# Entrypoint, timeout and environment variables
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  timeout: 240s
  args: ['compute', 'instances', 
          'create-with-container', 'my-vm-name',
          '--container-image', 
          'europe-west1-docker.pkg.dev/tactile-atlas-428811-g4/github.com/andrewmarkallen/marka.berlin:$COMMIT_SHA']
  env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'europe-west1-docker.pkg.dev/tactile-atlas-428811-g4/github.com/andrewmarkallen/marka.berlin:$COMMIT_SHA'
